[tool.poetry]
name = "openbb-yfinance"
version = "1.5.0"
description = "yfinance extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "openbb_yfinance" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
yfinance = "0.2.58"
openbb-core = "^1.5.1"
curl-adapter = ">=1.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
yfinance = "openbb_yfinance:yfinance_provider"
